config/routes.rb
Rails.application.routes.draw do

  
  resources :publicdomains
  root 'static_pages#home'

  get 'ldap/build/:id' => 'ldap#build'
  get 'ldap/create/:id' => 'ldap#create'
  get 'ldap/delete/:id' => 'ldap#destroy'
  get 'ldap/overwrite/:id' => 'ldap#overwrite'
  get 'users/index'
  get 'users/show' => 'users#show'
  get 'settings' => 'static_pages#settings'
  
  resources :ldapservers
  resources :ldap
  resources :newusers
  resources :grants
  resources :sites
  resources :companies
  
  devise_for :users

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


def home
end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>DASHBOARD</h1>
  <p>NewReq Dashboard</p>
  <p><%= link_to 'Request New User', new_newuser_path, class: "btn btn-lg btn-primary" %></p>
  
</div>

app/views/static_pages/settings.html.erb
<br>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">NewReq Settings</h3>
  </div>
  <div class="panel-body">
    
    
    <ul class="nav nav-pills">
      <li role="presentation"><a href="#">System Setting</a></li>
      <li role="presentation"><a href="#">SMTP Setting</a></li>
    </ul>
    
    
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">LDAP Settings</h3>
  </div>
  <div class="panel-body">
    
    
    <ul class="nav nav-pills">
      <li role="presentation"><%= link_to 'LDAP Servers', ldapservers_path %></a></li>
      <li role="presentation"><a href="#">Organizational Units</a></li>
      <li role="presentation"><%= link_to 'Public Domains', publicdomains_path %></li>
    </ul>
    
    
  </div>
</div>