config/routes.rb
Rails.application.routes.draw do

  
  resources :publicdomains
  root 'static_pages#home'

  get 'ldap/build/:id' => 'ldap#build'
  get 'ldap/create/:id' => 'ldap#create'
  get 'ldap/delete/:id' => 'ldap#destroy'
  get 'ldap/overwrite/:id' => 'ldap#overwrite'
  get 'users/index'
  get 'users/show' => 'users#show'
  get 'settings' => 'static_pages#settings'
  
  resources :ldapservers
  resources :ldap
  resources :newusers
  resources :grants
  resources :sites
  resources :companies
  
  devise_for :users

end

app/models/ldapserver.rb
class Ldapserver < ActiveRecord::Base
    has_many :newusers
end

app/controllers/ldapservers_controller.rb
class LdapserversController < ApplicationController
  before_action :set_ldapserver, only: [:show, :edit, :update, :destroy]

  # GET /ldapservers
  # GET /ldapservers.json
  def index
    @ldapservers = Ldapserver.all
  end

  # GET /ldapservers/1
  # GET /ldapservers/1.json
  def show
    
    require 'net/ldap'
    ldap = Net::LDAP.new(:host => @ldapserver.host, :port => @ldapserver.port)
    if ldap.bind( :method => :simple, 
                  :username => @ldapserver.username,
                  :password => @ldapserver.password,
                  :connect_timeout => 3)
                  # authentication succeeded
                  @ldaptest = 1
                  @message = ldap.get_operation_result.message
    else
      # authentication failed
      @ldaptest = 0
      @message = ldap.get_operation_result.message
    end

    
  end

  # GET /ldapservers/new
  def new
    @ldapserver = Ldapserver.new
  end

  # GET /ldapservers/1/edit
  def edit
  end

  # POST /ldapservers
  # POST /ldapservers.json
  def create
    @ldapserver = Ldapserver.new(ldapserver_params)

    respond_to do |format|
      if @ldapserver.save
        format.html { redirect_to @ldapserver, notice: 'Ldapserver was successfully created.' }
        format.json { render :show, status: :created, location: @ldapserver }
      else
        format.html { render :new }
        format.json { render json: @ldapserver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ldapservers/1
  # PATCH/PUT /ldapservers/1.json
  def update
    respond_to do |format|
      if @ldapserver.update(ldapserver_params)
        format.html { redirect_to @ldapserver, notice: 'Ldapserver was successfully updated.' }
        format.json { render :show, status: :ok, location: @ldapserver }
      else
        format.html { render :edit }
        format.json { render json: @ldapserver.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  # DELETE /ldapservers/1
  # DELETE /ldapservers/1.json
  def destroy
    @ldapserver.destroy
    respond_to do |format|
      format.html { redirect_to ldapservers_url, notice: 'Ldapserver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ldapserver
      @ldapserver = Ldapserver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ldapserver_params
      params.require(:ldapserver).permit(:domain, :host, :port, :attributename, :base, :username, :password, :method, :description)
    end
end

app/helpers/ldapservers_helper.rb
module LdapserversHelper
end

app/views/ldapservers/_form.html.erb
<%= form_for(@ldapserver) do |f| %>
  <% if @ldapserver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ldapserver.errors.count, "error") %> prohibited this ldapserver from being saved:</h2>

      <ul>
      <% @ldapserver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain, class: "form-control" %>
   <p>Example: intranet.local</p>
  </div>
  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host, class: "form-control" %>
    <p>Example: 172.16.0.1</p>
  </div>
  <div class="field">
    <%= f.label :port %><br>
    <%= f.text_field :port, class: "form-control" %>
    <p>Example: 389</p>
  </div>
  <div class="field">
    <%= f.label "Login Attribute" %><br>
    <%= f.select :attributename, [['sAMAccountName','sAMAccountName']], {class: "form-control"} %>
  </div>
  <div class="field">
    <%= f.label "Base DN" %><br>
    <%= f.text_field :base, class: "form-control" %>
    <p>Example: CN=Users,DC=intranet,DC=local</p>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %>
    <p>Example: CN=NewReq Admin,CN=Users,DC=intranet,DC=local</p>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :method %><br>
    <%= f.select :method, [['Simple','simple'],['Anonymous','anonymous']], {class: "form-control"} %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/ldapservers/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1>Editing LDAP Server</h1>
        <br>
        <%= render 'form' %>
        <br>
        <%= link_to 'Back', ldapservers_path, class: "btn btn-default" %>
    </div>
</div>
    

app/views/ldapservers/index.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<div class="container">
<h1>LDAP Servers Settings</h1>
<br>
<%= link_to 'New Ldapserver', new_ldapserver_path, class: "btn btn-lg btn-primary" %>
<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Description</th>
      <th>Domain</th>
      <th>Host</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @ldapservers.each do |ldapserver| %>
      <tr>
        <td><%= ldapserver.description %></td>
        <td><%= ldapserver.domain %></td>
        <td><%= ldapserver.host %></td>
        <td><%= link_to 'Show', ldapserver, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_ldapserver_path(ldapserver), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', ldapserver, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/ldapservers/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h4>New LDAP Server</h4>
        <%= render 'form' %>
        <br>
        <br>
        <%= link_to 'Back', ldapservers_path, class: "btn btn-default" %>
    </div>
</div>

app/views/ldapservers/show.html.erb
<p id="notice"><%= notice %></p>

<BR>
<BR>
  

<% if @ldaptest == 1 %>
<div class="alert alert-success" role="alert">
<p><strong>Status:</strong> <%= @message %></p>
</div>
<%  else %>
<div class="alert alert-danger" role="alert">
<p><strong>Status:</strong> <%= @message %></p>
</div>
<%  end %>

<BR>

<p>
  <strong>Description:</strong>
  <%= @ldapserver.description %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @ldapserver.domain %>
</p>

<p>
  <strong>Host:</strong>
  <%= @ldapserver.host %>
</p>

<p>
  <strong>Port:</strong>
  <%= @ldapserver.port %>
</p>

<p>
  <strong>Login Attribute:</strong>
  <%= @ldapserver.attributename %>
</p>

<p>
  <strong>Base DN:</strong>
  <%= @ldapserver.base %>
</p>

<p>
  <strong>Username:</strong>
  <%= @ldapserver.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @ldapserver.password %>
</p>

<p>
  <strong>Method:</strong>
  <%= @ldapserver.method %>

</p>


<%= link_to 'Edit', edit_ldapserver_path(@ldapserver), class: "btn btn-warning" %> |
<%= link_to 'Back', ldapservers_path, class: "btn btn-default" %>