config/routes.rb
Rails.application.routes.draw do

  
  resources :publicdomains
  root 'static_pages#home'

  get 'ldap/build/:id' => 'ldap#build'
  get 'ldap/create/:id' => 'ldap#create'
  get 'ldap/delete/:id' => 'ldap#destroy'
  get 'ldap/overwrite/:id' => 'ldap#overwrite'
  get 'users/index'
  get 'users/show' => 'users#show'
  get 'settings' => 'static_pages#settings'
  
  resources :ldapservers
  resources :ldap
  resources :newusers
  resources :grants
  resources :sites
  resources :companies
  
  devise_for :users

end

app/views/layouts/_header.html.erb
 <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to 'NewReq Portal', root_path, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <%= link_to 'Home', root_path %>
                    </li>

                    <li>
                        <%= link_to 'Request New User', new_newuser_path %>
                    </li>


                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Places <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'Companies', companies_path %></li>
                            <li><%= link_to 'Sites / Locations', sites_path %></li>
                        </ul>
                    </li>



                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to 'User Creation Requests', newusers_path %></li>
                            <li><%= link_to 'Approvers / Admin', grants_path %></li>
                            <li><%= link_to 'Users Who Have Signed', users_index_path %></li>
                        </ul>
                    </li>

                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resources <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                          <li><%= link_to 'Resources Category' %></li>
                          <li><%= link_to 'Resources' %></li>
                          <li><%= link_to 'Resources Profile' %></li>
                        <li role="separator" class="divider"></li>
                        </ul>
                    </li>
                    
                    
                     <li>
                        <%= link_to 'Administration', settings_path %>
                    </li>
                    
                    
                    <% if user_signed_in? %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
                            <%= current_user.username %> 
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
                            </li>
                            <li>
                                <a href="#">Account Settings</a>
                            </li>
                        </ul>
                    </li>
                    <% else %>
                        <li>
                            <%= link_to 'Sign in', new_user_session_path %>
                        </li>
                    <% end %>
                    
                    
                    
                    
                    
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <br><br><br>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div> 
  </body>
</html>